x-common-variables: &common-variables
  FRONTEND_PORT: ${FRONTEND_PORT:-8080}
  BACKEND_PORT: ${BACKEND_PORT:-5000}
  NGINX_PORT: ${NGINX_PORT:-8100}
  NGINX_SSL_PORT: ${NGINX_SSL_PORT:-443}
  

services:
  backend:
    build: ./backend
    container_name: carbonitor-backend 
    restart: always
    env_file:
      - ./backend/.env
    environment:
      <<: *common-variables
    ports: 
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    volumes:
      - ./backend:/backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: carbonitor-frontend
    env_file:
      - ./frontend/.env
    environment:
      <<: *common-variables
      ENV: dev
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "${FRONTEND_PORT:-8080}:${FRONTEND_PORT:-8080}"
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: carbonitor-proxy
    environment:
      <<: *common-variables
    ports:
      - "${NGINX_PORT:-8100}:${NGINX_PORT:-8100}"
      - "${NGINX_SSL_PORT:-443}:${NGINX_SSL_PORT:-443}"  # Optional SSL port
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro  # Optional: Mount SSL certificates
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mysql_data:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge

