"""empty message

Revision ID: c0ecc8e10e47
Revises: ca5633b3acc3
Create Date: 2025-01-27 13:35:35.776182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c0ecc8e10e47'
down_revision: Union[str, None] = 'ca5633b3acc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'user_created')
    op.drop_column('products', 'date_updated')
    op.drop_column('products', 'date_created')
    op.drop_column('products', 'user_updated')
    op.add_column('roles', sa.Column('permissions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'permissions')
    op.add_column('products', sa.Column('user_updated', mysql.CHAR(length=36), nullable=True))
    op.add_column('products', sa.Column('date_created', mysql.TIMESTAMP(), nullable=True))
    op.add_column('products', sa.Column('date_updated', mysql.TIMESTAMP(), nullable=True))
    op.add_column('products', sa.Column('user_created', mysql.CHAR(length=36), nullable=True))
    # ### end Alembic commands ###
