"""empty message

Revision ID: 43589cee3cc6
Revises: b3628974aac6
Create Date: 2025-03-20 17:54:18.765899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43589cee3cc6'
down_revision: Union[str, None] = 'b3628974aac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_created', sa.Integer(), nullable=True),
    sa.Column('user_id_updated', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_version', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('filter', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id_created'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_updated'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_filters')
    # ### end Alembic commands ###
