"""empty message

Revision ID: fac1bbcb2951
Revises: 43589cee3cc6
Create Date: 2025-03-25 12:18:43.782270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fac1bbcb2951'
down_revision: Union[str, None] = '43589cee3cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildups', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('buildups', sa.Column('classification', sa.JSON(), nullable=True))
    op.add_column('buildups', sa.Column('comment', sa.String(length=255), nullable=True))
    op.add_column('buildups', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('buildups', sa.Column('quantity', sa.Float(precision=10), nullable=False))
    op.add_column('buildups', sa.Column('unit', sa.String(length=255), nullable=True))
    op.add_column('buildups', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.add_column('buildups', sa.Column('products', sa.JSON(), nullable=True))
    op.add_column('buildups', sa.Column('results', sa.JSON(), nullable=True))
    op.drop_column('buildups', 'buildup_description')
    op.drop_column('buildups', 'buildup_id')
    op.drop_column('buildups', 'buildup_unit')
    op.drop_column('buildups', 'buildup_name')
    op.drop_column('buildups', 'buildup_parts')
    op.drop_column('buildups', 'buildup_url')
    op.drop_column('buildups', 'buildup_quantity')
    op.drop_column('buildups', 'buildup_classification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildups', sa.Column('buildup_classification', mysql.JSON(), nullable=False))
    op.add_column('buildups', sa.Column('buildup_quantity', mysql.FLOAT(precision=20, scale=10), nullable=True))
    op.add_column('buildups', sa.Column('buildup_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('buildups', sa.Column('buildup_parts', mysql.JSON(), nullable=False))
    op.add_column('buildups', sa.Column('buildup_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('buildups', sa.Column('buildup_unit', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('buildups', sa.Column('buildup_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('buildups', sa.Column('buildup_description', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('buildups', 'results')
    op.drop_column('buildups', 'products')
    op.drop_column('buildups', 'meta_data')
    op.drop_column('buildups', 'unit')
    op.drop_column('buildups', 'quantity')
    op.drop_column('buildups', 'description')
    op.drop_column('buildups', 'comment')
    op.drop_column('buildups', 'classification')
    op.drop_column('buildups', 'name')
    # ### end Alembic commands ###
