"""empty message

Revision ID: ca5633b3acc3
Revises: 7b41d79a1722
Create Date: 2025-01-14 14:54:15.386676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca5633b3acc3'
down_revision: Union[str, None] = '7b41d79a1722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'epd_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'epdx',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('products', 'epd_sourceName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'products', 'users', ['user_id_updated'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['user_id_created'], ['id'])
    op.drop_column('products', 'user_created')
    op.drop_column('products', 'date_created')
    op.drop_column('products', 'date_updated')
    op.drop_column('products', 'user_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_updated', mysql.CHAR(length=36), nullable=True))
    op.add_column('products', sa.Column('date_updated', mysql.TIMESTAMP(), nullable=True))
    op.add_column('products', sa.Column('date_created', mysql.TIMESTAMP(), nullable=True))
    op.add_column('products', sa.Column('user_created', mysql.CHAR(length=36), nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'epd_sourceName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'epdx',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('products', 'epd_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
