"""empty message

Revision ID: b3628974aac6
Revises: c6e13c8956ce
Create Date: 2025-03-06 10:18:31.107764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3628974aac6'
down_revision: Union[str, None] = 'c6e13c8956ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('epd_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'epd_description')
    # ### end Alembic commands ###
