"""empty message

Revision ID: 5f070384fb9a
Revises: e2b4fa2a42e4
Create Date: 2025-03-29 13:42:39.524830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5f070384fb9a'
down_revision: Union[str, None] = 'e2b4fa2a42e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_created', sa.Integer(), nullable=True),
    sa.Column('user_id_updated', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_version', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('filter', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id_created'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_updated'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id_created', sa.Integer(), nullable=True),
    sa.Column('user_id_updated', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_version', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('maps', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id_created'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_updated'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('model_filters')
    op.alter_column('buildups', 'quantity',
               existing_type=mysql.FLOAT(),
               server_default=sa.text('1.0'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildups', 'quantity',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.create_table('model_filters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id_created', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id_updated', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('source', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('source_version', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('filter', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_created'], ['users.id'], name='model_filters_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id_updated'], ['users.id'], name='model_filters_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('mappings')
    op.drop_table('filters')
    # ### end Alembic commands ###
