"""empty message

Revision ID: b8408ba00ed7
Revises: c0ecc8e10e47
Create Date: 2025-02-12 10:17:38.780298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8408ba00ed7'
down_revision: Union[str, None] = 'c0ecc8e10e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_roles_ibfk_1', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_ibfk_2', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_ibfk_2', 'user_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_roles_ibfk_1', 'user_roles', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
