"""empty message

Revision ID: e2b4fa2a42e4
Revises: fac1bbcb2951
Create Date: 2025-03-25 16:40:01.760675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2b4fa2a42e4'
down_revision: Union[str, None] = 'fac1bbcb2951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildups', 'quantity',
               existing_type=mysql.FLOAT(),
               server_default=sa.text('1.0'),
               existing_nullable=False)
    op.alter_column('model_filters', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('model_filters', 'filter',
               existing_type=mysql.JSON(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_filters', 'filter',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('model_filters', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('buildups', 'quantity',
               existing_type=mysql.FLOAT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
