"""empty message

Revision ID: 7b41d79a1722
Revises: 
Create Date: 2025-01-14 14:42:44.033812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7b41d79a1722'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('models', 'model_quantity',
               existing_type=mysql.FLOAT(precision=20, scale=10),
               nullable=True)
    op.alter_column('models', 'model_classification',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('models', 'model_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('models', 'model_location',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('models', 'model_formatVersion',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('models', 'model_lcaMethod',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('models', 'model_classificationSystem',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('models', 'model_lifeCycleStages',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('models', 'model_impactCategories',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('models', 'model_emissionParts',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('models', 'model_lifeSpan',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'models', 'users', ['user_id_created'], ['id'])
    op.create_foreign_key(None, 'models', 'users', ['user_id_updated'], ['id'])
    op.drop_column('models', 'date_created')
    op.drop_column('models', 'user_created')
    op.drop_column('models', 'date_updated')
    op.drop_column('models', 'user_updated')
    op.add_column('products', sa.Column('user_id_created', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('user_id_updated', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('products', 'status',
               existing_type=mysql.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'epd_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'epd_declaredUnit',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'epd_version',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'epd_publishedDate',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'epd_validUntil',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'epd_standard',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'epd_comment',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'epd_location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'epd_formatVersion',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('products', 'epd_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'epdx',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('products', 'epd_sourceName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'epd_sourceUrl',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'epd_subtype',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'products', 'users', ['user_id_created'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['user_id_updated'], ['id'])
    op.drop_column('products', 'date_created')
    op.drop_column('products', 'user_created')
    op.drop_column('products', 'date_updated')
    op.drop_column('products', 'user_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_updated', mysql.CHAR(length=36), nullable=True))
    op.add_column('products', sa.Column('date_updated', mysql.TIMESTAMP(), nullable=True))
    op.add_column('products', sa.Column('user_created', mysql.CHAR(length=36), nullable=True))
    op.add_column('products', sa.Column('date_created', mysql.TIMESTAMP(), nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'epd_subtype',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'epd_sourceUrl',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'epd_sourceName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'epdx',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('products', 'epd_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'epd_formatVersion',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('products', 'epd_location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'epd_comment',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'epd_standard',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'epd_validUntil',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'epd_publishedDate',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'epd_version',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'epd_declaredUnit',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'epd_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'status',
               existing_type=mysql.VARCHAR(length=255),
               server_default=sa.text("'draft'"),
               existing_nullable=False)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'user_id_updated')
    op.drop_column('products', 'user_id_created')
    op.add_column('models', sa.Column('user_updated', mysql.CHAR(length=36), nullable=True))
    op.add_column('models', sa.Column('date_updated', mysql.TIMESTAMP(), nullable=True))
    op.add_column('models', sa.Column('user_created', mysql.CHAR(length=36), nullable=True))
    op.add_column('models', sa.Column('date_created', mysql.TIMESTAMP(), nullable=True))
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.alter_column('models', 'model_lifeSpan',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('models', 'model_emissionParts',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('models', 'model_impactCategories',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('models', 'model_lifeCycleStages',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('models', 'model_classificationSystem',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('models', 'model_lcaMethod',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('models', 'model_formatVersion',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('models', 'model_location',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('models', 'model_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('models', 'model_classification',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('models', 'model_quantity',
               existing_type=mysql.FLOAT(precision=20, scale=10),
               nullable=False)
    # ### end Alembic commands ###
