"""empty message

Revision ID: c76b02e8d41f
Revises: 5f070384fb9a
Create Date: 2025-03-29 16:44:15.925937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c76b02e8d41f'
down_revision: Union[str, None] = '5f070384fb9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildups', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               server_default=sa.text('1.0'),
               existing_nullable=False)

    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_migration', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.drop_column('test_migration')

    with op.batch_alter_table('buildups', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'1'"),
               existing_nullable=False)

    # ### end Alembic commands ###
