"""empty message

Revision ID: 3e4576be6a7b
Revises: e7bc29a88263
Create Date: 2025-03-02 20:01:07.061799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4576be6a7b'
down_revision: Union[str, None] = 'e7bc29a88263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_associations_ibfk_1', 'category_associations', type_='foreignkey')
    op.create_foreign_key(None, 'category_associations', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category_associations', type_='foreignkey')
    op.create_foreign_key('category_associations_ibfk_1', 'category_associations', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
